/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_window_menu (void);
GtkWidget* create_gestion_compte (void);
GtkWidget* create_Gestion_Calendrier (void);
GtkWidget* create_supprimer_compte__ (void);
GtkWidget* create_colorselectiondialog1 (void);
GtkWidget* create_colorselectiondialog2 (void);

GtkWidget* create_window101 (void);
GtkWidget* create_window102 (void);
GtkWidget* create_window103 (void);
GtkWidget* create_window104 (void);
GtkWidget* create_window105 (void);

GtkWidget* create_window1 (void);
GtkWidget* create_windowm2 (void);
GtkWidget* create_windowm3 (void);
GtkWidget* create_windowm4 (void);
GtkWidget* create_windowm5 (void);
GtkWidget* create_Horraire (void);
GtkWidget* create_Rendez_vousM (void);
GtkWidget* create_ajouter_horaire (void);
GtkWidget* create_modifier_fiche (void);
GtkWidget* create_modif_m (void);
GtkWidget* create_mod_hm (void);

GtkWidget* create_window1s (void);
GtkWidget* create_window2s (void);
GtkWidget* create_window3s (void);
GtkWidget* create_window4s (void);
GtkWidget* create_window5s (void);
GtkWidget* create_window6s (void);
GtkWidget* create_window7s (void);
GtkWidget* create_window8s (void);
GtkWidget* create_window9s (void);



GtkWidget* create_window1m (void);
GtkWidget* create_window2m (void);
GtkWidget* create_window3m (void);
GtkWidget* create_window5m (void);
GtkWidget* create_window7m (void);
GtkWidget* create_window10m (void);
GtkWidget* create_window11m (void);
GtkWidget* create_window12m (void);
GtkWidget* create_window1111m (void);


