/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_espace_kine (void);
GtkWidget* create_window_menu (void);
GtkWidget* create_Gestions_comptes (void);
GtkWidget* create_ajouter_ADMIN (void);
GtkWidget* create_modifier (void);

GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_window7 (void);
