/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *button0;
  GtkWidget *image23;
  GtkWidget *checkbutton1;
  GtkWidget *button1;
  GtkWidget *alignment19;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label35;
  GtkWidget *image22;
  GtkWidget *label3;
  GtkWidget *image28;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (login, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (login), _("MY GYM"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 488, 312);
  gtk_widget_set_size_request (entry1, 300, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 488, 400);
  gtk_widget_set_size_request (entry2, 300, 35);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("mot de passe"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 368, 400);
  gtk_widget_set_size_request (label2, 88, 32);

  label1 = gtk_label_new_with_mnemonic (_("login"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 376, 312);
  gtk_widget_set_size_request (label1, 70, 35);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0.54, 0.68);
  gtk_misc_set_padding (GTK_MISC (label1), 21, 1);

  button0 = gtk_button_new ();
  gtk_widget_show (button0);
  gtk_fixed_put (GTK_FIXED (fixed1), button0, 920, 24);
  gtk_widget_set_size_request (button0, 50, 30);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (button0), image23);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("show password"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 800, 408);
  gtk_widget_set_size_request (checkbutton1, 128, 24);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 520, 472);
  gtk_widget_set_size_request (button1, 150, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button1), alignment19);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("login"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox18), label35, FALSE, FALSE, 0);

  image22 = create_pixmap (login, "photo13.jpg");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed1), image22, 112, 0);
  gtk_widget_set_size_request (image22, 792, 248);

  label3 = gtk_label_new ("");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 504, 592);
  gtk_widget_set_size_request (label3, 160, 48);

  image28 = create_pixmap (login, "photo13.jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed1), image28, 96, 392);
  gtk_widget_set_size_request (image28, 21, 21);

  g_signal_connect ((gpointer) button0, "clicked",
                    G_CALLBACK (quitter_page1),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (password),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (logiin),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label1), entry1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (login, label2, "label2");
  GLADE_HOOKUP_OBJECT (login, label1, "label1");
  GLADE_HOOKUP_OBJECT (login, button0, "button0");
  GLADE_HOOKUP_OBJECT (login, image23, "image23");
  GLADE_HOOKUP_OBJECT (login, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (login, button1, "button1");
  GLADE_HOOKUP_OBJECT (login, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (login, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (login, image18, "image18");
  GLADE_HOOKUP_OBJECT (login, label35, "label35");
  GLADE_HOOKUP_OBJECT (login, image22, "image22");
  GLADE_HOOKUP_OBJECT (login, label3, "label3");
  GLADE_HOOKUP_OBJECT (login, image28, "image28");

  return login;
}

GtkWidget*
create_espace_kine (void)
{
  GtkWidget *espace_kine;
  GtkWidget *fixed3;
  GtkWidget *label6;

  espace_kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_kine), _("espace_kine"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (espace_kine), fixed3);

  label6 = gtk_label_new (_("espace kin\303\251"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 200, 56);
  gtk_widget_set_size_request (label6, 120, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_kine, espace_kine, "espace_kine");
  GLADE_HOOKUP_OBJECT (espace_kine, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (espace_kine, label6, "label6");

  return espace_kine;
}

GtkWidget*
create_window_menu (void)
{
  GtkWidget *window_menu;
  GtkWidget *fixed6;
  GtkWidget *label10;
  GtkWidget *button11;
  GtkWidget *button40;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label33;
  GtkWidget *button41;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label34;
  GtkWidget *button10;

  window_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_menu, 500, 201);
  gtk_window_set_title (GTK_WINDOW (window_menu), _("Menu"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window_menu), fixed6);

  label10 = gtk_label_new (_("Bienvenu admin !"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed6), label10, 104, 0);
  gtk_widget_set_size_request (label10, 200, 48);

  button11 = gtk_button_new_with_mnemonic (_("Gestion de la salle"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 120, 136);
  gtk_widget_set_size_request (button11, 160, 56);

  button40 = gtk_button_new ();
  gtk_widget_show (button40);
  gtk_fixed_put (GTK_FIXED (fixed6), button40, 360, 8);
  gtk_widget_set_size_request (button40, 120, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button40), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox16), label33, FALSE, FALSE, 0);

  button41 = gtk_button_new ();
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed6), button41, 360, 72);
  gtk_widget_set_size_request (button41, 120, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button41), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-justify-left", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox17), label34, FALSE, FALSE, 0);

  button10 = gtk_button_new_with_mnemonic (_("Gestion comptes"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed6), button10, 120, 64);
  gtk_widget_set_size_request (button10, 160, 56);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (Gestion_salle),
                    NULL);
  g_signal_connect ((gpointer) button40, "clicked",
                    G_CALLBACK (menu_quitter),
                    NULL);
  g_signal_connect ((gpointer) button41, "clicked",
                    G_CALLBACK (deconnexion_6),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (gestion_comptes),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_menu, window_menu, "window_menu");
  GLADE_HOOKUP_OBJECT (window_menu, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_menu, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_menu, button11, "button11");
  GLADE_HOOKUP_OBJECT (window_menu, button40, "button40");
  GLADE_HOOKUP_OBJECT (window_menu, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window_menu, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window_menu, image16, "image16");
  GLADE_HOOKUP_OBJECT (window_menu, label33, "label33");
  GLADE_HOOKUP_OBJECT (window_menu, button41, "button41");
  GLADE_HOOKUP_OBJECT (window_menu, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window_menu, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window_menu, image17, "image17");
  GLADE_HOOKUP_OBJECT (window_menu, label34, "label34");
  GLADE_HOOKUP_OBJECT (window_menu, button10, "button10");

  return window_menu;
}

GtkWidget*
create_Gestions_comptes (void)
{
  GtkWidget *Gestions_comptes;
  GtkWidget *fixed19;
  GtkWidget *notebook1;
  GtkWidget *fixed20;
  GtkWidget *button83;
  GtkWidget *alignment25;
  GtkWidget *hbox24;
  GtkWidget *image26;
  GtkWidget *label48;
  GtkWidget *button84;
  GtkWidget *alignment26;
  GtkWidget *hbox25;
  GtkWidget *image27;
  GtkWidget *label49;
  GtkWidget *scrolledwindow5;
  GtkWidget *viewport5;
  GtkWidget *fixed21;
  GtkWidget *treeview8;
  GtkWidget *button81;
  GtkWidget *alignment23;
  GtkWidget *hbox22;
  GtkWidget *image24;
  GtkWidget *label46;
  GtkWidget *admin;
  GtkWidget *fixed24;
  GtkWidget *scrolledwindow6;
  GtkWidget *viewport6;
  GtkWidget *fixed25;
  GtkWidget *treeview9;
  GtkWidget *button87;
  GtkWidget *alignment27;
  GtkWidget *hbox26;
  GtkWidget *image29;
  GtkWidget *label57;
  GtkWidget *label41;
  GtkWidget *fixed26;
  GtkWidget *label42;
  GtkWidget *fixed27;
  GtkWidget *label43;
  GtkWidget *empty_notebook_page;
  GtkWidget *label44;
  GtkWidget *label45;

  Gestions_comptes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestions_comptes, 1257, 480);
  gtk_window_set_title (GTK_WINDOW (Gestions_comptes), _("Gestions comptes"));
  gtk_window_set_default_size (GTK_WINDOW (Gestions_comptes), 50, 70);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (Gestions_comptes), fixed19);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed19), notebook1, 8, 72);
  gtk_widget_set_size_request (notebook1, 1290, 597);

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed20);

  button83 = gtk_button_new ();
  gtk_widget_show (button83);
  gtk_fixed_put (GTK_FIXED (fixed20), button83, 416, 120);
  gtk_widget_set_size_request (button83, 120, 29);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button83), alignment25);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox24);

  image26 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox24), image26, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox24), label48, FALSE, FALSE, 0);

  button84 = gtk_button_new ();
  gtk_widget_show (button84);
  gtk_fixed_put (GTK_FIXED (fixed20), button84, 416, 192);
  gtk_widget_set_size_request (button84, 120, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button84), alignment26);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox25);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox25), image27, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox25), label49, FALSE, FALSE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_fixed_put (GTK_FIXED (fixed20), scrolledwindow5, 24, 56);
  gtk_widget_set_size_request (scrolledwindow5, 352, 448);

  viewport5 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), viewport5);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (viewport5), fixed21);

  treeview8 = gtk_tree_view_new ();
  gtk_widget_show (treeview8);
  gtk_fixed_put (GTK_FIXED (fixed21), treeview8, 16, 0);
  gtk_widget_set_size_request (treeview8, 1000, 1000);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview8), TRUE);

  button81 = gtk_button_new ();
  gtk_widget_show (button81);
  gtk_fixed_put (GTK_FIXED (fixed20), button81, 416, 48);
  gtk_widget_set_size_request (button81, 120, 30);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button81), alignment23);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox22);

  image24 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox22), image24, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox22), label46, FALSE, FALSE, 0);

  admin = gtk_label_new (_("Gestion Administrateur"));
  gtk_widget_show (admin);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), admin);
  gtk_widget_set_size_request (admin, 200, 40);
  gtk_misc_set_alignment (GTK_MISC (admin), 0.41, 0.5);

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed24);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_fixed_put (GTK_FIXED (fixed24), scrolledwindow6, 24, 56);
  gtk_widget_set_size_request (scrolledwindow6, 352, 448);

  viewport6 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport6);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), viewport6);

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (viewport6), fixed25);

  treeview9 = gtk_tree_view_new ();
  gtk_widget_show (treeview9);
  gtk_fixed_put (GTK_FIXED (fixed25), treeview9, 16, 0);
  gtk_widget_set_size_request (treeview9, 1000, 1000);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview9), TRUE);

  button87 = gtk_button_new ();
  gtk_widget_show (button87);
  gtk_fixed_put (GTK_FIXED (fixed24), button87, 416, 48);
  gtk_widget_set_size_request (button87, 120, 30);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button87), alignment27);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox26);

  image29 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox26), image29, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox26), label57, FALSE, FALSE, 0);

  label41 = gtk_label_new (_("Gestion Kin\303\251"));
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label41);
  gtk_widget_set_size_request (label41, 200, 40);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed26);

  label42 = gtk_label_new (_("Gestion Medecin"));
  gtk_widget_show (label42);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label42);
  gtk_widget_set_size_request (label42, 200, 40);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed27);

  label43 = gtk_label_new (_("Gestion Adh\303\251rant"));
  gtk_widget_show (label43);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label43);
  gtk_widget_set_size_request (label43, 200, 40);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label44 = gtk_label_new (_("Gestion Nutritioniste"));
  gtk_widget_show (label44);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label44);
  gtk_widget_set_size_request (label44, 200, 40);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label45 = gtk_label_new (_("Gestion Coache"));
  gtk_widget_show (label45);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label45);
  gtk_widget_set_size_request (label45, 200, 40);

  g_signal_connect ((gpointer) button83, "clicked",
                    G_CALLBACK (modifier_ADMIN),
                    NULL);
  g_signal_connect ((gpointer) button84, "clicked",
                    G_CALLBACK (supprimer_ADMIN),
                    NULL);
  g_signal_connect ((gpointer) treeview8, "row_activated",
                    G_CALLBACK (on_treeview8_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button81, "clicked",
                    G_CALLBACK (ajouter_ADMIN),
                    NULL);
  g_signal_connect ((gpointer) treeview9, "row_activated",
                    G_CALLBACK (on_treeview8_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button87, "clicked",
                    G_CALLBACK (ajouter_KIN__),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestions_comptes, Gestions_comptes, "Gestions_comptes");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, button83, "button83");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, image26, "image26");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label48, "label48");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, button84, "button84");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, image27, "image27");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label49, "label49");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, viewport5, "viewport5");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, treeview8, "treeview8");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, button81, "button81");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, image24, "image24");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label46, "label46");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, admin, "admin");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, viewport6, "viewport6");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, treeview9, "treeview9");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, button87, "button87");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, image29, "image29");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label57, "label57");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label41, "label41");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label42, "label42");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label44, "label44");
  GLADE_HOOKUP_OBJECT (Gestions_comptes, label45, "label45");

  return Gestions_comptes;
}

GtkWidget*
create_ajouter_ADMIN (void)
{
  GtkWidget *ajouter_ADMIN;
  GtkWidget *fixed22;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *entry11;
  GtkWidget *label52;
  GtkWidget *button85;
  GtkWidget *label53;

  ajouter_ADMIN = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_ADMIN), _("Ajouter Administrateur"));

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (ajouter_ADMIN), fixed22);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed22), entry9, 232, 40);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed22), entry10, 232, 96);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label50 = gtk_label_new (_("login"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed22), label50, 80, 48);
  gtk_widget_set_size_request (label50, 49, 17);

  label51 = gtk_label_new (_("password"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed22), label51, 80, 88);
  gtk_widget_set_size_request (label51, 64, 24);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed22), entry11, 232, 144);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label52 = gtk_label_new (_("CIN"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed22), label52, 80, 144);
  gtk_widget_set_size_request (label52, 49, 17);

  button85 = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (button85);
  gtk_fixed_put (GTK_FIXED (fixed22), button85, 168, 264);
  gtk_widget_set_size_request (button85, 74, 29);

  label53 = gtk_label_new ("");
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed22), label53, 136, 184);
  gtk_widget_set_size_request (label53, 96, 56);

  g_signal_connect ((gpointer) button85, "clicked",
                    G_CALLBACK (valider_ajouter_ADMIN),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_ADMIN, ajouter_ADMIN, "ajouter_ADMIN");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, label50, "label50");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, label51, "label51");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, label52, "label52");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, button85, "button85");
  GLADE_HOOKUP_OBJECT (ajouter_ADMIN, label53, "label53");

  return ajouter_ADMIN;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed23;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *entry15;
  GtkWidget *label56;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *button86;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier "));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (modifier), fixed23);
  GTK_WIDGET_SET_FLAGS (fixed23, GTK_CAN_DEFAULT);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed23), entry12, 176, 56);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed23), entry13, 176, 112);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed23), entry15, 176, 168);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  label56 = gtk_label_new (_("CIN :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed23), label56, 88, 176);
  gtk_widget_set_size_request (label56, 49, 17);

  label55 = gtk_label_new (_("password :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed23), label55, 88, 120);
  gtk_widget_set_size_request (label55, 88, 16);

  label54 = gtk_label_new (_("login :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed23), label54, 88, 56);
  gtk_widget_set_size_request (label54, 64, 24);

  button86 = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (button86);
  gtk_fixed_put (GTK_FIXED (fixed23), button86, 240, 248);
  gtk_widget_set_size_request (button86, 74, 29);

  g_signal_connect ((gpointer) button86, "clicked",
                    G_CALLBACK (valider_modifier_ADMIN),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (modifier, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (modifier, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (modifier, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (modifier, label56, "label56");
  GLADE_HOOKUP_OBJECT (modifier, label55, "label55");
  GLADE_HOOKUP_OBJECT (modifier, label54, "label54");
  GLADE_HOOKUP_OBJECT (modifier, button86, "button86");

  return modifier;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *button6;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *label3;
  GtkWidget *button3;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *button4;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *button5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window1"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  button6 = gtk_button_new_with_mnemonic (_("d\303\251connexion"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 352, 264);
  gtk_widget_set_size_request (button6, 104, 45);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 1, 115);
  gtk_widget_set_size_request (scrolledwindow1, 198, 200);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 8, 0);
  gtk_widget_set_size_request (treeview1, 1000, 1000);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);

  label3 = gtk_label_new (_("espace kinesitherapeute"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 32, 24);
  gtk_widget_set_size_request (label3, 208, 16);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 288, 32);
  gtk_widget_set_size_request (button3, 232, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button3), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("consulter les fiches medicales"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 288, 104);
  gtk_widget_set_size_request (button4, 232, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button4), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("horaires et rendez-vous"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 288, 176);
  gtk_widget_set_size_request (button5, 232, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("calendrier"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (consulter_les_fiches_medicales),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (horaires_et_rendez_vous),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (calendrier),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window2, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window2, image1, "image1");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window2, image2, "image2");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (window2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window2, image3, "image3");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed4;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("consulter les fiches medicales"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window3), fixed4);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow2, 104, 80);
  gtk_widget_set_size_request (scrolledwindow2, 200, 200);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 2000, 2000);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window3, treeview2, "treeview2");

  return window3;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport2;
  GtkWidget *fixed7;
  GtkWidget *treeview3;
  GtkWidget *button8;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label14;
  GtkWidget *button7;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *button9;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label16;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("Horaires et rendez-vous"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow3, 120, 104);
  gtk_widget_set_size_request (scrolledwindow3, 200, 200);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport2);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed7);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview3, 0, 0);
  gtk_widget_set_size_request (treeview3, 456, 176);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed5), button8, 48, 368);
  gtk_widget_set_size_request (button8, 96, 24);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button8), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 272, 368);
  gtk_widget_set_size_request (button7, 80, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button7), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 136, 416);
  gtk_widget_set_size_request (button9, 96, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button9), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (modifier),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (ajouter),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (supprimer),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window5, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (window5, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window5, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window5, button8, "button8");
  GLADE_HOOKUP_OBJECT (window5, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window5, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window5, image4, "image4");
  GLADE_HOOKUP_OBJECT (window5, label14, "label14");
  GLADE_HOOKUP_OBJECT (window5, button7, "button7");
  GLADE_HOOKUP_OBJECT (window5, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window5, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window5, image5, "image5");
  GLADE_HOOKUP_OBJECT (window5, label15, "label15");
  GLADE_HOOKUP_OBJECT (window5, button9, "button9");
  GLADE_HOOKUP_OBJECT (window5, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window5, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window5, image6, "image6");
  GLADE_HOOKUP_OBJECT (window5, label16, "label16");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed6;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("calendrier"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed8;
  GtkWidget *label4;
  GtkWidget *entry3;
  GtkWidget *label5;
  GtkWidget *entry4;
  GtkWidget *label7;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label9;
  GtkWidget *label6;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label10;
  GtkWidget *label8;
  GtkWidget *combobox1;
  GtkWidget *button10;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("ajouter un rendez-vous"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window7), fixed8);
  gtk_widget_set_size_request (fixed8, 548, 277);

  label4 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed8), label4, 32, 40);
  gtk_widget_set_size_request (label4, 41, 17);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3, 120, 40);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label5 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed8), label5, 16, 80);
  gtk_widget_set_size_request (label5, 80, 24);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4, 120, 80);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label7 = gtk_label_new (_("Jour"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed8), label7, 184, 152);
  gtk_widget_set_size_request (label7, 56, 24);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton1, 240, 152);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton2, 360, 152);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label9 = gtk_label_new (_("annes"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed8), label9, 432, 160);
  gtk_widget_set_size_request (label9, 41, 17);

  label6 = gtk_label_new (_("Date de rendez-vous :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed8), label6, 8, 144);
  gtk_widget_set_size_request (label6, 160, 40);

  spinbutton3_adj = gtk_adjustment_new (2018, 2018, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton3, 488, 152);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label10 = gtk_label_new (_("Heure de rendez-vous"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed8), label10, 0, 200);
  gtk_widget_set_size_request (label10, 176, 16);

  label8 = gtk_label_new (_("mois"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed8), label8, 312, 152);
  gtk_widget_set_size_request (label8, 48, 24);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox1, 200, 184);
  gtk_widget_set_size_request (combobox1, 256, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("9h==>12h15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("14h==>17j15"));

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed8), button10, 432, 248);
  gtk_widget_set_size_request (button10, 108, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button10), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (confirmer_),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window7, label4, "label4");
  GLADE_HOOKUP_OBJECT (window7, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window7, label5, "label5");
  GLADE_HOOKUP_OBJECT (window7, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window7, label7, "label7");
  GLADE_HOOKUP_OBJECT (window7, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window7, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window7, label9, "label9");
  GLADE_HOOKUP_OBJECT (window7, label6, "label6");
  GLADE_HOOKUP_OBJECT (window7, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window7, label10, "label10");
  GLADE_HOOKUP_OBJECT (window7, label8, "label8");
  GLADE_HOOKUP_OBJECT (window7, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window7, button10, "button10");
  GLADE_HOOKUP_OBJECT (window7, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window7, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window7, image7, "image7");
  GLADE_HOOKUP_OBJECT (window7, label17, "label17");

  return window7;
}
